services:
  - type: web
    name: foosball-backend
    env: go
    region: oregon
    plan: free
    buildCommand: go build -o main .
    startCommand: ./main
    envVars:
      - key: JWT_SECRET
        value: my-super-secret-ke
    autoDeploy: true
